apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: xxxxx-your-cluster-name-xxxxxxx
  region: xxxx-your-aws-region-xxxxxx
  version: "1.31"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
 - name: coredns
