apiVersion: batch/v1
kind: Job
metadata:
  name: tomcat
spec:
  template:
    spec:
      containers:
      - name: tomcat
        image: quay.io/johncilium/tomcat:latest
      restartPolicy: OnFailure