apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
spec:
  selector:
    matchLabels:
      app: cassandra
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.11.14
        ports:
        - containerPort: 80

